# Site settings
title: The Legend of Codes
header-img: img/home-bg.png
email: abijahstokes@gmail.com
copyright_name: abijahstokes
description: > # this means to ignore newlines until "baseurl:"
  From Nothingness to the League of Legendary Coders
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  abijahstokes
learn_profile: abijahstokes
email_username: abijahstokes@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
